--Q1. What is the total revenue generated by male vs. female customers?
Select 
	gender,
	Sum(purchase_amount) as revenue
From customer
Group By gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
Select
	customer_id,
	purchase_amount
From customer
Where discount_applied='Yes' and purchase_amount>=(Select Avg(purchase_amount) From customer)

-- Q3. Which are the top 5 products with the highest average review rating?
Select Top 5
	item_purchased,
	Round(Avg(review_rating),3) as average_product_rating
From customer
Group By item_purchased
Order By average_product_rating Desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
Select 
	shipping_type,
	Avg(purchase_amount) as average_purchase_amount_shipping
From customer
Where shipping_type in ('Express','Standard')
Group By shipping_type

